# general configuration
url: http://www.gamecopypolish.com
baseurl: ''
title: "Game Copy Polish"

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/assets/images/ian-face.png"
  # author will appear under the avatar (optional)
  author: "Ian Tyrrell"
  # tagline will appear under the title (optional)
  tagline: "Copyediting, proofreading, and general copy polish (for your games)"
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
